[book]
authors = ["Zehui2020"]
language = "en"
multilingual = false
src = "src"
title = "FYP_Q3_Documentation"

[output.html]
no-section-label = true
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]

[output.html.fold]
enable = true